// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: tgcdgkhsjdrrsasqixtp

class SupabaseConfig {
  static const String supabaseUrl = 'https://tgcdgkhsjdrrsasqixtp.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnY2Rna2hzamRycnNhc3FpeHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4NDUxMTgsImV4cCI6MjA4OTQyMTExOH0.ZPDHRbnbQlRUyyvg1AfQWyNC8cR-Lg08ikuVX8htsms';
}
